name: ESLint
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: npm install
      run: |
        cd system/static/js
        npm install
    - name: run tests
      run: |
        cd system/static/js
        npm run format:check
        npm run lint:check
